addison: add missing instances from manifest in the framework compatibility and set FMC 2
Error: The following instances are in the device manifest but not specified in framework compatibility matrix:
    android.hardware.health@2.0::IHealth/backup
    com.motorola.mod@1.0::IModManager/default
    motorola.hardware.camera.provider@2.4::ICameraProvider/legacy/0
    motorola.hardware.health@1.0::IMotHealth/default
    motorola.hardware.mods_camera.provider@2.4::ICameraProvider/mods_camera/0
    vendor.nxp.nxpnfc@1.0::INxpNfc/default
    vendor.xperience.power@1.0::IXPeriencePower/default

Signed-off-by: klozz <shaclone707@gmail.com>